language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
# whitelist
branches:
  only:
    - master
    - development
    - travis
jobs:
  include:
    - stage: Run tests
      name: "Run front-end unit tests"
      script: npm test
    - stage: Build
      name: "Build front-end"
      #install: 
      #- npm install
      script: npm run build
    - stage: Deploy front
      name: "Push front-end statics to back-end rep"
      script: echo "Push front to back"
      # git push build https://github.com/pasunmaa/full-stack-open-2018-blogilista/tree/master/build/static
      # https://gist.github.com/Maumagnaguagno/84a9807ed71d233e5d3f
      # git push "https://${TRAVIS_SECURE_TOKEN_NAME}@${GH_REPO}" master > /dev/null 2>&1
      # https://docs.travis-ci.com/user/deployment/releases/